title: "Brian's Carpenter Workshop"
remote_theme: just-the-docs/just-the-docs
#color_scheme: "dark"
# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/blaylockbk/Carpenter_Workshop"
  "ğŸ’¬ Discussions":
    - "//github.com/blaylockbk/Carpenter_Workshop/discussions"
  "â“ Issues":
    - "//github.com/blaylockbk/Carpenter_Workshop/issues"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/blaylockbk/Carpenter_Workshop" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

callouts:
  admonition:
    color: blue
  attention:
    color: green
  caution:
    color: yellow
  danger:
    title: ğŸ’€ Danger
    color: red
  error:
    title: ğŸš¨ Error
    color: red
  hint:
    title: Hint
    color: green
  important:
    title: âœ¨ Important
    color: blue
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: blue
  warning:
    title: ğŸš§ Warning
    color: red

